### ISSUE TITLE
希望添加 JSON 文件以允许用户可以通过其他主页跳转至本主页

### ISSUE THREAD

**Issue by WForst-Breeze** [Joker2184/UpdateHomepage#3]
你好！我是新预设 ***PCL 新功能说明书*** 的作者 WForst-Breeze，我希望可以在我的主页中添加一个跳转至你的主页的按钮，以允许用户可以跳转到你的主页查看完整更新日志。但你的主页同目录下没有相应的 Json 文件，导致我这个想法暂时无法实现，因此希望在你的主页文件的同目录下添加一个同名 JSON 文件，以允许用户通过其他主页跳转至本主页。算是一个小联动吧~ 感激不尽

**Comment by MoYuan-CN** [comment]
有……啊？

**Comment by Joker2184** [comment]
> 有……啊？

（没有....啊

**Comment by Joker2184** [comment]
> 你好！我是新预设 _**PCL 新功能说明书**_ 的作者 WForst-Breeze，我希望可以在我的主页中添加一个跳转至你的主页的按钮，以允许用户可以跳转到你的主页查看完整更新日志。但你的主页同目录下没有相应的 Json 文件，导致我这个想法暂时无法实现，因此希望在你的主页文件的同目录下添加一个同名 JSON 文件，以允许用户通过其他主页跳转至本主页。算是一个小联动吧~ 感激不尽

~~大佬 膜拜~~
马上搞.jpg((((
一开始原本没考虑跳转的问题.jpg
~~荣幸之至~~

**Comment by Joker2184** [comment]
@WForst-Breeze 

你可以通过 此链接 打开本主页
```
https://UpdateHomepage.pages.dev/UpdateHomepage.json
```

**Comment by WForst-Breeze** [comment]
感谢——！
